In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
variable_1 = np.array([10,20,30,40,50])
print(variable_1)

[10 20 30 40 50]


In [4]:
print(type(variable_1))

<class 'numpy.ndarray'>


In [5]:
variable_2 = np.array([60, "Bilal", 3.14, True])
print(variable_2)

['60' 'Bilal' '3.14' 'True']


In [6]:
list_1 = [10, "Bilal", 3.14, True]
print(list_1)

[10, 'Bilal', 3.14, True]


In [7]:
print(type(variable_2))
print(type(list_1))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
print(variable_1) 
variable_1[0] = 100
print(variable_1)
print(len(variable_1))

[10 20 30 40 50]
[100  20  30  40  50]
5


In [12]:
#Shape gives the dimensions of the array
print(variable_1.shape)
print(variable_1.dtype)
#Adding a number to every element of the array
print(variable_1) #Before Adding a number
print(variable_1 + 10)

(5,)
int64
[100  20  30  40  50]
[110  30  40  50  60]


In [14]:
array_1 = np.array([5,7,8,9])
array_2 = np.array([3,5,7,9])
print(array_1 + array_2) #Adding two arrays
print(array_1 - array_2) #Subtracting two arrays
print(array_1 * array_2) #Multiplying two arrays
print(array_1 / array_2) #Dividing two arrays

[ 8 12 15 18]
[2 2 1 0]
[15 35 56 81]
[1.66666667 1.4        1.14285714 1.        ]


In [15]:
print(np.sum(array_1)) #Sum of all elements in the array

29
